IRO-1705 Added styles for tooltip.
iron-fish/ui-kit pull request #12
Opened 2022-03-25 13:27 UTC by azhurauski-sc

![demo1](https://user-images.githubusercontent.com/39185158/160125249-5261f17c-0f8a-4f9f-8c4e-8311d748249a.gif)

2022-03-25 15:52 UTC, ndemidovich-sc approved these changes

2022-03-28 20:18 UTC, brekk requested changes
Minor request, otherwise things look good!

2022-03-28 20:18 UTC, brekk commented on package.json
> +    "eslint-plugin-react": "^7.29.4",
Minor but can we keep these static? (that is, without `^` preceding them?) You can also run `nps meta.bureaucracy` to do so automatically.

2022-03-29 17:56 UTC, brekk approved these changes
Looks like there's a file in conflict, but otherwise this is ready to merge.

2022-03-30 07:51 UTC, merged