Added possibility to limit dropdown height, pass props to popover elements.
iron-fish/ui-kit pull request #130
Opened 2023-05-18 09:09 UTC by azhurauski-sc

Additional props is no required, added as it could be used.

2023-05-18 16:22 UTC, skylarrichard123 requested changes
Can we increase the amount of list items we show from 2 to 5 before we need to scroll in the dropdown?
<img width="465" alt="Screen Shot 2023-05-18 at 9 21 40 AM" src="https://github.com/iron-fish/ui-kit/assets/75860817/0909f729-66d3-4e25-9afb-c22c03f5c9d5">

2023-05-19 08:10 UTC, azhurauski-sc commented
> Can we increase the amount of list items we show from 2 to 5 before we need to scroll in the dropdown? <img alt="Screen Shot 2023-05-18 at 9 21 40 AM" width="465" src="https://user-images.githubusercontent.com/75860817/239296168-0909f729-66d3-4e25-9afb-c22c03f5c9d5.png">

Yes, by default if will be full list visible and amount of items to show could be configure via parameter.

2023-05-19 10:20 UTC, ndemidovich-sc approved these changes

2023-05-23 16:15 UTC, skylarrichard123 approved these changes

2023-05-23 16:53 UTC, merged