IRO-1711 Added button variant for sidebar navigation item.
iron-fish/ui-kit pull request #15
Opened 2022-03-30 11:10 UTC by azhurauski-sc

<details>
<summary>Demo</summary>

![demo1](https://user-images.githubusercontent.com/39185158/160821423-23fad1c2-8aee-4ae4-a998-e1a66c5d88a9.gif)

 </<details>

2022-03-30 12:40 UTC, ndemidovich-sc requested changes

2022-03-30 12:40 UTC, ndemidovich-sc commented on theme/components/Button.ts
> +    sideBarNavItem: props => ({
May be better to rename it? Ex. `navItem`

2022-03-30 12:40 UTC, ndemidovich-sc commented on components/SideBarInfoIcon.tsx
> +      }
For me some of this properties must be in `theme\components\[componentName].ts`.
Also this component cannot be customized via properties. For example `height`, `width`.

2022-03-30 12:40 UTC, ndemidovich-sc commented on components/SideBarInfoIcon.tsx
> +const SideBarInfoIcon: FC<SideBarInfoIconProps> = ({ label }) => {
This component is very similar to Chakra UI component - [`Badge`](https://chakra-ui.com/docs/components/data-display/badge).
May be better to reuse `Badge` component?

2022-04-01 11:45 UTC, ndemidovich-sc approved these changes

2022-04-01 17:02 UTC, brekk approved these changes

2022-04-04 07:40 UTC, merged