(IRO-2590) Added loading state to mnemonic view.
iron-fish/ui-kit pull request #75
Opened 2022-09-16 14:05 UTC by azhurauski-sc

2022-09-16 16:37 UTC, skylarrichard123 requested changes
Right now it just looks like the loading state is 0 data. It should be the skeleton loader like we have in the data tables

2022-09-20 06:56 UTC, ndemidovich-sc approved these changes

2022-09-20 06:56 UTC, ndemidovich-sc commented on stories/MnemonicPhrase.stories.tsx
> +          w="600px"
```suggestion
          w="37.5rem"
```

2022-09-20 13:04 UTC, skylarrichard123 approved these changes

2022-09-20 13:47 UTC, merged